#!/bin/bash
# fancontrol-setup — dynamically generates /etc/fancontrol with correct hwmon numbers
# hwmon numbering is unstable across boots; this script finds devices by name
# and writes the config before fancontrol.service starts.
#
# Runs as ExecStartPre= in fancontrol.service override.

set -euo pipefail

# Find hwmon number by name
find_hwmon() {
    local target_name="$1"
    for h in /sys/class/hwmon/hwmon*; do
        local name
        name=$(cat "$h/name" 2>/dev/null) || continue
        if [ "$name" = "$target_name" ]; then
            basename "$h"
            return 0
        fi
    done
    echo "ERROR: hwmon device '$target_name' not found" >&2
    return 1
}

# Board detection — only run on LS1046A
compat="/proc/device-tree/compatible"
if [ ! -f "$compat" ] || ! tr '\0' '\n' < "$compat" | grep -q "fsl,ls1046a"; then
    exit 0  # not our board, skip silently
fi

EMC=$(find_hwmon "emc2305") || exit 1
CORE=$(find_hwmon "core_cluster") || exit 1

EMC_PATH=$(readlink -f "/sys/class/hwmon/$EMC/device" | sed 's|^/sys/||')
CORE_PATH=$(readlink -f "/sys/class/hwmon/$CORE/device" | sed 's|^/sys/||')

cat > /etc/fancontrol << EOF
# Auto-generated by fancontrol-setup — do not edit manually
# EMC2305 PWM fan → core-cluster thermal zone
# Linear ramp: 40°C (off) → 51 PWM (spin-up) → 255 PWM (80°C full)
INTERVAL=10
DEVPATH=${EMC}=${EMC_PATH} ${CORE}=${CORE_PATH}
DEVNAME=${EMC}=emc2305 ${CORE}=core_cluster
FCTEMPS=${EMC}/pwm1=${CORE}/temp1_input
FCFANS=${EMC}/pwm1=${EMC}/fan1_input
MINTEMP=${EMC}/pwm1=40
MAXTEMP=${EMC}/pwm1=80
MINSTART=${EMC}/pwm1=51
MINSTOP=${EMC}/pwm1=34
MINPWM=${EMC}/pwm1=0
MAXPWM=${EMC}/pwm1=255
AVERAGE=${EMC}/pwm1=1
EOF

echo "fancontrol-setup: EMC2305=$EMC core_cluster=$CORE → /etc/fancontrol"
